/**
 * Mock DataForSEO API responses for testing
 * Based on official API documentation
 */

import type {
  RelatedKeywordsResponse,
  KeywordSuggestionsResponse,
  SerpResponse,
  BacklinksSummaryResponse,
} from "../types/dataforseo.js";

export const mockRelatedKeywordsResponse: RelatedKeywordsResponse = {
  version: "0.1.20241104",
  status_code: 20000,
  status_message: "Ok.",
  time: "0.8234 sec.",
  cost: 0.001,
  tasks_count: 1,
  tasks_error: 0,
  tasks: [
    {
      id: "12041234-1234-5678-1234-123456789012",
      status_code: 20000,
      status_message: "Ok.",
      time: "0.7821 sec.",
      cost: 0.001,
      result_count: 1,
      path: ["v3", "dataforseo_labs", "google", "related_keywords", "live"],
      data: {
        keyword: "json formatter",
        location_code: 2840,
        language_code: "en",
      },
      result: [
        {
          se_type: "google",
          seed_keyword: "json formatter",
          seed_keyword_data: {
            se_type: "google",
            keyword: "json formatter",
            keyword_info: {
              se_type: "google",
              last_updated_time: "2024-10-15 12:00:00 +00:00",
              competition: 0.15,
              competition_level: "LOW",
              cpc: 2.5,
              search_volume: 22000,
              low_top_of_page_bid: 0.5,
              high_top_of_page_bid: 3.0,
              categories: [13886, 13719],
              monthly_searches: [
                { year: 2024, month: 10, search_volume: 22000 },
                { year: 2024, month: 9, search_volume: 20000 },
                { year: 2024, month: 8, search_volume: 21000 },
              ],
              search_volume_trend: { monthly: 10, quarterly: 5, yearly: 15 },
            },
            keyword_properties: {
              se_type: "google",
              core_keyword: "json formatter",
              synonym_clustering_algorithm: "text_processing",
              keyword_difficulty: 25,
              detected_language: "en",
              is_another_language: false,
            },
            serp_info: {
              se_type: "google",
              check_url: "https://www.google.com/search?q=json%20formatter",
              serp_item_types: ["organic", "featured_snippet"],
              se_results_count: 128000000,
              last_updated_time: "2024-10-15 12:00:00 +00:00",
              previous_updated_time: "2024-10-08 12:00:00 +00:00",
            },
            search_intent_info: {
              se_type: "google",
              main_intent: "transactional",
              foreign_intent: ["informational"],
              last_updated_time: "2024-10-15 12:00:00 +00:00",
            },
          },
          location_code: 2840,
          language_code: "en",
          total_count: 85,
          items_count: 3,
          items: [
            {
              se_type: "google",
              keyword_data: {
                se_type: "google",
                keyword: "json formatter online",
                keyword_info: {
                  se_type: "google",
                  last_updated_time: "2024-10-15 12:00:00 +00:00",
                  competition: 0.12,
                  competition_level: "LOW",
                  cpc: 1.8,
                  search_volume: 8100,
                  low_top_of_page_bid: 0.3,
                  high_top_of_page_bid: 2.5,
                  categories: [13886],
                  monthly_searches: [
                    { year: 2024, month: 10, search_volume: 8100 },
                    { year: 2024, month: 9, search_volume: 7500 },
                  ],
                  search_volume_trend: { monthly: 8, quarterly: 3, yearly: 10 },
                },
                keyword_properties: {
                  se_type: "google",
                  core_keyword: "json formatter",
                  synonym_clustering_algorithm: "text_processing",
                  keyword_difficulty: 22,
                  detected_language: "en",
                  is_another_language: false,
                },
                serp_info: null,
                search_intent_info: {
                  se_type: "google",
                  main_intent: "transactional",
                  foreign_intent: null,
                  last_updated_time: "2024-10-15 12:00:00 +00:00",
                },
              },
              depth: 1,
              related_keywords: ["json beautifier", "json validator"],
            },
            {
              se_type: "google",
              keyword_data: {
                se_type: "google",
                keyword: "json beautifier",
                keyword_info: {
                  se_type: "google",
                  last_updated_time: "2024-10-15 12:00:00 +00:00",
                  competition: 0.1,
                  competition_level: "LOW",
                  cpc: 1.5,
                  search_volume: 5400,
                  low_top_of_page_bid: 0.25,
                  high_top_of_page_bid: 2.0,
                  categories: [13886],
                  monthly_searches: [
                    { year: 2024, month: 10, search_volume: 5400 },
                  ],
                  search_volume_trend: { monthly: 5, quarterly: 2, yearly: 8 },
                },
                keyword_properties: {
                  se_type: "google",
                  core_keyword: "json formatter",
                  synonym_clustering_algorithm: "text_processing",
                  keyword_difficulty: 20,
                  detected_language: "en",
                  is_another_language: false,
                },
                serp_info: null,
                search_intent_info: {
                  se_type: "google",
                  main_intent: "transactional",
                  foreign_intent: null,
                  last_updated_time: "2024-10-15 12:00:00 +00:00",
                },
              },
              depth: 1,
              related_keywords: ["pretty print json"],
            },
            {
              se_type: "google",
              keyword_data: {
                se_type: "google",
                keyword: "format json",
                keyword_info: {
                  se_type: "google",
                  last_updated_time: "2024-10-15 12:00:00 +00:00",
                  competition: 0.08,
                  competition_level: "LOW",
                  cpc: 1.2,
                  search_volume: 3600,
                  low_top_of_page_bid: 0.2,
                  high_top_of_page_bid: 1.8,
                  categories: [13886],
                  monthly_searches: [
                    { year: 2024, month: 10, search_volume: 3600 },
                  ],
                  search_volume_trend: { monthly: 3, quarterly: 1, yearly: 5 },
                },
                keyword_properties: {
                  se_type: "google",
                  core_keyword: "json formatter",
                  synonym_clustering_algorithm: "text_processing",
                  keyword_difficulty: 18,
                  detected_language: "en",
                  is_another_language: false,
                },
                serp_info: null,
                search_intent_info: {
                  se_type: "google",
                  main_intent: "transactional",
                  foreign_intent: null,
                  last_updated_time: "2024-10-15 12:00:00 +00:00",
                },
              },
              depth: 1,
              related_keywords: null,
            },
          ],
        },
      ],
    },
  ],
};

export const mockSerpResponse: SerpResponse = {
  version: "0.1.20241104",
  status_code: 20000,
  status_message: "Ok.",
  time: "1.2345 sec.",
  cost: 0.002,
  tasks_count: 1,
  tasks_error: 0,
  tasks: [
    {
      id: "22041234-1234-5678-1234-123456789012",
      status_code: 20000,
      status_message: "Ok.",
      time: "1.1234 sec.",
      cost: 0.002,
      result_count: 1,
      path: ["v3", "serp", "google", "organic", "live", "regular"],
      data: {
        keyword: "json formatter",
        location_code: 2840,
        language_code: "en",
      },
      result: [
        {
          keyword: "json formatter",
          type: "organic",
          se_domain: "google.com",
          location_code: 2840,
          language_code: "en",
          check_url: "https://www.google.com/search?q=json%20formatter",
          datetime: "2024-10-15 12:00:00 +00:00",
          spell: null,
          refinement_chips: null,
          item_types: ["organic", "featured_snippet", "related_searches"],
          se_results_count: 128000000,
          pages_count: 1,
          items_count: 10,
          items: [
            {
              type: "organic",
              rank_group: 1,
              rank_absolute: 1,
              position: "left",
              xpath: "/html/body/div[4]",
              domain: "jsonformatter.org",
              title: "JSON Formatter & Validator",
              description: "Format and validate your JSON data with our free online tool...",
              url: "https://jsonformatter.org/",
              breadcrumb: "jsonformatter.org",
              is_image: false,
              is_video: false,
              is_featured_snippet: false,
              is_malicious: false,
              is_web_story: false,
              amp_version: false,
              rating: null,
              links: null,
              about_this_result: null,
              main_domain: "jsonformatter.org",
              relative_url: "/",
              cached_pages: null,
              related_search_url: null,
              etv: 15000,
              impressions_etv: 22000,
              estimated_paid_traffic_cost: 45000,
              rank_changes: { previous_rank_absolute: 1, is_new: false, is_up: false, is_down: false },
              backlinks_info: { referring_domains: 1250, referring_main_domains: 980, referring_pages: 5400, dofollow: 4200, backlinks: 8500, time_update: "2024-10-15" },
              rank_info: { page_rank: 45, main_domain_rank: 52 },
            },
            {
              type: "organic",
              rank_group: 2,
              rank_absolute: 2,
              position: "left",
              xpath: "/html/body/div[5]",
              domain: "jsonlint.com",
              title: "JSONLint - The JSON Validator",
              description: "JSONLint is the free online validator and reformatter for JSON...",
              url: "https://jsonlint.com/",
              breadcrumb: "jsonlint.com",
              is_image: false,
              is_video: false,
              is_featured_snippet: false,
              is_malicious: false,
              is_web_story: false,
              amp_version: false,
              rating: null,
              links: null,
              about_this_result: null,
              main_domain: "jsonlint.com",
              relative_url: "/",
              cached_pages: null,
              related_search_url: null,
              etv: 12000,
              impressions_etv: 18000,
              estimated_paid_traffic_cost: 35000,
              rank_changes: { previous_rank_absolute: 2, is_new: false, is_up: false, is_down: false },
              backlinks_info: { referring_domains: 890, referring_main_domains: 720, referring_pages: 3200, dofollow: 2800, backlinks: 5600, time_update: "2024-10-15" },
              rank_info: { page_rank: 38, main_domain_rank: 45 },
            },
            {
              type: "organic",
              rank_group: 3,
              rank_absolute: 3,
              position: "left",
              xpath: "/html/body/div[6]",
              domain: "codebeautify.org",
              title: "JSON Formatter - Code Beautify",
              description: "JSON Formatter & Beautifier with tree view...",
              url: "https://codebeautify.org/jsonviewer",
              breadcrumb: "codebeautify.org › jsonviewer",
              is_image: false,
              is_video: false,
              is_featured_snippet: false,
              is_malicious: false,
              is_web_story: false,
              amp_version: false,
              rating: null,
              links: null,
              about_this_result: null,
              main_domain: "codebeautify.org",
              relative_url: "/jsonviewer",
              cached_pages: null,
              related_search_url: null,
              etv: 8000,
              impressions_etv: 12000,
              estimated_paid_traffic_cost: 22000,
              rank_changes: { previous_rank_absolute: 4, is_new: false, is_up: true, is_down: false },
              backlinks_info: { referring_domains: 650, referring_main_domains: 520, referring_pages: 2100, dofollow: 1800, backlinks: 3800, time_update: "2024-10-15" },
              rank_info: { page_rank: 32, main_domain_rank: 48 },
            },
          ],
        },
      ],
    },
  ],
};

export const mockBacklinksSummaryResponse: BacklinksSummaryResponse = {
  version: "0.1.20241104",
  status_code: 20000,
  status_message: "Ok.",
  time: "0.5234 sec.",
  cost: 0.001,
  tasks_count: 1,
  tasks_error: 0,
  tasks: [
    {
      id: "32041234-1234-5678-1234-123456789012",
      status_code: 20000,
      status_message: "Ok.",
      time: "0.4821 sec.",
      cost: 0.001,
      result_count: 1,
      path: ["v3", "backlinks", "summary", "live"],
      data: { target: "jsonformatter.org" },
      result: [
        {
          target: "jsonformatter.org",
          first_seen: "2015-03-15 10:00:00 +00:00",
          lost_date: null,
          rank: 52,
          backlinks: 8500,
          backlinks_spam_score: 12,
          crawled_pages: 45,
          info: {
            server: "cloudflare",
            cms: null,
            platform_type: ["web"],
            ip_address: "104.21.23.45",
            country: "US",
            is_ip: false,
            target_spam_score: 8,
          },
          internal_links_count: 120,
          external_links_count: 25,
          broken_backlinks: 45,
          broken_pages: 3,
          referring_domains: 1250,
          referring_domains_nofollow: 180,
          referring_main_domains: 980,
          referring_main_domains_nofollow: 120,
          referring_ips: 890,
          referring_subnets: 650,
          referring_pages: 5400,
          referring_pages_nofollow: 680,
          referring_links_tld: { com: 3200, org: 850, net: 420, io: 380 },
          referring_links_types: { anchor: 4800, image: 520, redirect: 80, form: 0, alternate: 0, canonical: 0 },
          referring_links_attributes: { nofollow: 680, noopener: 120, noreferrer: 85, external: 2100, ugc: 15, sponsored: 25 },
          referring_links_platform_types: { web: 4800, blog: 380, news: 120, forum: 100 },
          referring_links_semantic_locations: { footer: 180, header: 95, content: 4125, sidebar: 400, nav: 200 },
          referring_links_countries: { US: 2800, UK: 580, DE: 420, IN: 380, FR: 220 },
        },
      ],
    },
  ],
};

// Low-opportunity keyword for testing filters
export const mockLowVolumeKeywordResponse: RelatedKeywordsResponse = {
  ...mockRelatedKeywordsResponse,
  tasks: [
    {
      ...mockRelatedKeywordsResponse.tasks[0],
      result: [
        {
          ...mockRelatedKeywordsResponse.tasks[0].result![0],
          items: [
            {
              se_type: "google",
              keyword_data: {
                se_type: "google",
                keyword: "obscure json tool",
                keyword_info: {
                  se_type: "google",
                  last_updated_time: "2024-10-15 12:00:00 +00:00",
                  competition: 0.05,
                  competition_level: "LOW",
                  cpc: 0.5, // Below min CPC threshold
                  search_volume: 100, // Below min volume threshold
                  low_top_of_page_bid: 0.1,
                  high_top_of_page_bid: 0.8,
                  categories: null,
                  monthly_searches: null,
                  search_volume_trend: null,
                },
                keyword_properties: {
                  se_type: "google",
                  core_keyword: "json tool",
                  synonym_clustering_algorithm: "text_processing",
                  keyword_difficulty: 5,
                  detected_language: "en",
                  is_another_language: false,
                },
                serp_info: null,
                search_intent_info: null,
              },
              depth: 1,
              related_keywords: null,
            },
          ],
        },
      ],
    },
  ],
};

// Error response
export const mockErrorResponse: RelatedKeywordsResponse = {
  version: "0.1.20241104",
  status_code: 40000,
  status_message: "You can set only one task at a time.",
  time: "0.0123 sec.",
  cost: 0,
  tasks_count: 1,
  tasks_error: 1,
  tasks: [
    {
      id: "42041234-1234-5678-1234-123456789012",
      status_code: 40501,
      status_message: "Invalid field: keyword",
      time: "0.0100 sec.",
      cost: 0,
      result_count: 0,
      path: ["v3", "dataforseo_labs", "google", "related_keywords", "live"],
      data: { keyword: "" },
      result: null,
    },
  ],
};
